pools:
  - name: rpoole
    vdevs:
      - type: mirror
        drives: [sdb, sdc]
      - type: mirror
        drives: [sdd, sde]
      - type: mirror
        drives: [sdf, sdg]
    datasets:
      - name: server

